name: banco_do_tempo_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter 
  flutter_slidable: ^0.5.7  
  firebase_picture_uploader: ^1.2.1
  firebase_auth: ^0.20.1
  cloud_firestore: ^0.16.0+1
  firebase_core: ^0.7.0
  firebase_storage: ^7.0.0
  equatable: ^2.0.0
  image_picker: ^0.6.7+22
  carousel_slider: ^3.0.0
  flutter_bloc: ^7.0.0
  email_validator: ^1.0.6
  meta: ^1.3.0
  photo_view: ^0.11.1

  intl: ^0.16.1 
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  flutter_svg: ^0.19.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.3

flutter:
  fonts:
    - family: DMSans
      fonts:
        - asset: assets/dm-sans-regular.ttf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/profile.png
    - assets/images/background.jpg
    - assets/images/main_bottom.png
    - assets/icons/
 
    
   




